image: rustlang/rust:nightly

services:
  - postgres:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - ./gather-prerequisites.sh
  - ./rename-database-host.sh
  - ./execute-data-import.sh

stages:
  - test

test:
  script:
    - cargo test --features "with-postgres with-sqlite"
    - cargo test --features "with-postgres"
    - cargo test --features "with-sqlite"

