name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install -y sqlite3 libsqlite3-0 libsqlite3-dev
    - name: Checkout sakila
      run: |
          git clone https://github.com/ivanceras/sakila.git
          sqlite3 sakila.db < sakila/sqlite-sakila-db/sqlite-sakila-schema.sql
          sqlite3 sakila.db < sakila/sqlite-sakila-db/sqlite-sakila-insert-data.sql
    - name: Build
      run: cargo build --all --all-features
    - name: Run tests
      run: cargo test --all --all-features
